
INSERT INTO `kecamatan` (`id`, `id_kota`, `nama`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 1, 'Kecamatan Alang-Alang Lebar', NULL, NULL, NULL),
(2, 1, 'Kecamatan Bukit Kecil', NULL, NULL, NULL),
(3, 1, 'Kecamatan Gandus', NULL, NULL, NULL),
(4, 1, 'Kecamatan Ilir Barat I', NULL, NULL, NULL),
(5, 1, 'Kecamatan Ilir Barat II', NULL, NULL, NULL),
(6, 1, 'Kecamatan Ilir Timur I', NULL, NULL, NULL),
(7, 1, 'Kecamatan Ilir Timur II', NULL, NULL, NULL),
(8, 1, 'Kecamatan Kalidoni', NULL, NULL, NULL),
(9, 1, 'Kecamatan Kemuning', NULL, NULL, NULL),
(10, 1, 'Kecamatan Kertapati', NULL, NULL, NULL),
(11, 1, 'Kecamatan Plaju', NULL, NULL, NULL),
(12, 1, 'Kecamatan Sako', NULL, NULL, NULL),
(13, 1, 'Kecamatan Seberang Ulu I', NULL, NULL, NULL),
(14, 1, 'Kecamatan Seberang Ulu II', NULL, NULL, NULL),
(15, 1, 'Kecamatan Sematang Borang', NULL, NULL, NULL),
(16, 1, 'Kecamatan Sukarami', NULL, NULL, NULL),
(30, 3, 'Kecamatan Bukit Raya', NULL, NULL, NULL),
(31, 3, 'Kecamatan Lima Puluh', NULL, NULL, NULL),
(32, 3, 'Kecamatan Marpoyan Damai', NULL, NULL, NULL),
(33, 3, 'Kecamatan Payung Sekaki', NULL, NULL, NULL),
(34, 3, 'Kecamatan Pekanbaru Kota', NULL, NULL, NULL),
(35, 3, 'Kecamatan Rumbai', NULL, NULL, NULL),
(36, 3, 'Kecamatan Rumbai Pesisir', NULL, NULL, NULL),
(37, 3, 'Kecamatan Sail', NULL, NULL, NULL),
(38, 3, 'Kecamatan Senapelan', NULL, NULL, NULL),
(39, 3, 'Kecamatan Sukajadi', NULL, NULL, NULL),
(40, 3, 'Kecamatan Tampan', NULL, NULL, NULL),
(41, 3, 'Kecamatan Tenayan Raya', NULL, NULL, NULL),
(42, 4, 'Kecamatan Bungus Teluk Kabung', NULL, NULL, NULL),
(43, 4, 'Kecamatan Koto Tangah', NULL, NULL, NULL),
(44, 4, 'Kecamatan Kuranji', NULL, NULL, NULL),
(45, 4, 'Kecamatan Lubuk Begalung', NULL, NULL, NULL),
(46, 4, 'Kecamatan Lubuk Kilangan', NULL, NULL, NULL),
(47, 4, 'Kecamatan Nanggalo', NULL, NULL, NULL),
(48, 4, 'Kecamatan Padang Barat', NULL, NULL, NULL),
(49, 4, 'Kecamatan Padang Selatan', NULL, NULL, NULL),
(50, 4, 'Kecamatan Padang Timur', NULL, NULL, NULL),
(51, 4, 'Kecamatan Padang Utara', NULL, NULL, NULL),
(52, 4, 'Kecamatan Pauh', NULL, NULL, NULL),
(54, 5, 'Kecamatan Cempaka Putih', NULL, NULL, NULL),
(55, 5, 'Kecamatan Gambir', NULL, NULL, NULL),
(56, 5, 'Kecamatan Johar Baru', NULL, NULL, NULL),
(57, 5, 'Kecamatan Kemayoran', NULL, NULL, NULL),
(58, 5, 'Kecamatan Menteng', NULL, NULL, NULL),
(59, 5, 'Kecamatan Sawah Besar', NULL, NULL, NULL),
(60, 5, 'Kecamatan Senen', NULL, NULL, NULL),
(61, 5, 'Kecamatan Tanah Abang', NULL, NULL, NULL),
(62, 6, 'Kecamatan Cengkareng', NULL, NULL, NULL),
(63, 6, 'Kecamatan Grogol Petamburan', NULL, NULL, NULL),
(64, 6, 'Kecamatan Kalideres', NULL, NULL, NULL),
(65, 6, 'Kecamatan Kebon Jeruk', NULL, NULL, NULL),
(66, 6, 'Kecamatan Kembangan', NULL, NULL, NULL),
(67, 6, 'Kecamatan Palmerah', NULL, NULL, NULL),
(68, 6, 'Kecamatan Taman Sari', NULL, NULL, NULL),
(69, 6, 'Kecamatan Tambora', NULL, NULL, NULL),
(70, 7, 'Kecamatan Cilincing', NULL, NULL, NULL),
(71, 7, 'Kecamatan Kelapa Gading', NULL, NULL, NULL),
(72, 7, 'Kecamatan Koja', NULL, NULL, NULL),
(73, 7, 'Kecamatan Pademangan', NULL, NULL, NULL),
(74, 7, ' Kecamatan Penjaringan', NULL, NULL, NULL),
(75, 7, 'Kecamatan Tanjung', NULL, NULL, NULL),
(76, 8, 'Kecamatan Cakung', NULL, NULL, NULL),
(77, 8, 'Kecamatan Cipayung', NULL, NULL, NULL),
(78, 8, 'Kecamatan Ciracas', NULL, NULL, NULL),
(79, 8, 'Kecamatan Duren Sawit', NULL, NULL, NULL),
(80, 8, 'Kecamatan Jatinegara', NULL, NULL, NULL),
(81, 8, 'Kecamatan Kramatjati', NULL, NULL, NULL),
(82, 8, 'Kecamatan Makasar', NULL, NULL, NULL),
(83, 8, 'Kecamatan Matraman', NULL, NULL, NULL),
(84, 8, 'Kecamatan Pasar Rebo', NULL, NULL, NULL),
(85, 8, 'Kecamatan Pulogadung', NULL, NULL, NULL);